; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.5 on Tue Oct 26 2021 20:15:19 GMT+0200 (Mitteleuropäische Sommerzeit)
M280 P0 S10 ; deploy BLTouch

