; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.5 on Tue Oct 26 2021 20:15:19 GMT+0200 (Mitteleuropäische Sommerzeit)
; Wait for set temperatures to be reached
M116 P0

