; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.5 on Tue Oct 26 2021 20:15:19 GMT+0200 (Mitteleuropäische Sommerzeit)
M561 ; clear any bed transform
G28 ; home
M401 ; deploy Z probe
G30 P1 X400 Y170 Z-99999 ; probe near a leadscrew
G30 P2 X51 Y345 Z-99999; probe near a leadscrew
G30 P0 X47 Y0 Z-99999 S3 ; probe near a leadscrew and calibrate 3 motors
M402 ; retract probe (omit if using bltouch)

M561 ; clear any bed transform
G29  ; probe the bed and enable compensation
M500 ; save bed compensation