; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.5 on Tue Oct 26 2021 20:15:19 GMT+0200 (Mitteleuropäische Sommerzeit)

